import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>   
    <html lang="en">
      <body
        className={`${poppins.className} bg-background text-foreground antialiased`}        
      >
        <ConvexClientProvider>
          <Provider>
            <Header />
            {children}
          </Provider>
        </ConvexClientProvider>
        
      </body>
    </html>
     </ClerkProvider>
  );
}
